# Generated by Django 6.0 on 2025-12-18 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_birth_date_user_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ (تومان)')),
                ('receipt_image', models.ImageField(upload_to='receipts/topup/', verbose_name='تصویر رسید پرداخت')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست شارژ کیف پول',
                'verbose_name_plural': 'درخواست\u200cهای شارژ کیف پول',
                'ordering': ['-created_at'],
            },
        ),
    ]
