# Generated by Django 6.0 on 2025-12-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_sitestats_satisfactionsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitestats',
            name='last_visit_date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ آخرین بازدید'),
        ),
        migrations.AddField(
            model_name='sitestats',
            name='today_visits',
            field=models.PositiveIntegerField(default=0, verbose_name='بازدیدهای امروز'),
        ),
        migrations.AlterField(
            model_name='sitestats',
            name='total_visits',
            field=models.PositiveBigIntegerField(default=0, verbose_name='کل بازدیدها'),
        ),
    ]
