# Generated by Django 5.2.8 on 2025-12-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='توضیحات اکانت و اطلاعات تحویل', null=True, verbose_name='توضیحات ادمین'),
        ),
    ]
