# Generated by Django 5.2.8 on 2025-12-26 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method'),
        ('products', '0005_product_show_in_hero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download_file',
            field=models.FileField(blank=True, help_text='فایل قابل دانلود برای مشتریان (فقط برای محصولات فایل)', null=True, upload_to='products/files/', verbose_name='فایل دانلود'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('account', 'اکانت'), ('file', 'فایل')], default='account', max_length=20, verbose_name='نوع محصول'),
        ),
        migrations.CreateModel(
            name='ProductDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
                ('first_download_at', models.DateTimeField(blank=True, null=True, verbose_name='اولین دانلود')),
                ('last_download_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین دانلود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دانلود محصول',
                'verbose_name_plural': 'دانلودهای محصولات',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
