# Generated by Django 5.2.8 on 2025-12-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('WALLET', 'کیف پول'), ('CARD', 'کارت به کارت'), ('ONLINE', 'درگاه مستقیم'), ('NONE', 'نامشخص')], default='NONE', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
