# Generated by Django 5.2.8 on 2025-12-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_note',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح نویسنده (برای این مقاله)'),
        ),
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, to='articles.article', verbose_name='مقالات مرتبط'),
        ),
    ]
