# Generated by Django 5.2.8 on 2025-12-26 22:04

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author_note_article_related_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='محتوا'),
        ),
    ]
