# Generated by Django 5.2.8 on 2025-12-27 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest_phone__isnull', True), ('user__isnull', False)), models.Q(('guest_phone__isnull', False), ('user__isnull', True)), _connector='OR'), name='chat_room_user_or_guest'),
        ),
    ]
