# Generated by Django 6.0 on 2025-12-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_hero',
            field=models.BooleanField(default=False, verbose_name='نمایش در اسلایدر هیرو'),
        ),
    ]
