# Generated by Django 6.0 on 2025-12-19 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ticket_ticketmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'آمار سایت',
                'verbose_name_plural': 'آمار سایت',
            },
        ),
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_satisfied', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نظرسنجی رضایت',
                'verbose_name_plural': 'نظرسنجی\u200cهای رضایت',
                'unique_together': {('user',)},
            },
        ),
    ]
