# Generated by Django 5.2.8 on 2025-12-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'بازدیدکننده',
                'verbose_name_plural': 'بازدیدکنندگان',
                'unique_together': {('ip_address', 'date')},
            },
        ),
    ]
